options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

# Push to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']

# Authenticate with GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'my-cluster', '--zone=us-central1-a']

# Deploy using kubectl
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes-config.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
