options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

# Push to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']

# Deploy to GKE (updated syntax)
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=kubernetes-config.yaml'
  - '--image=gcr.io/$PROJECT_ID/my-app'
  - '--location=us-central1'
  - '--cluster=my-cluster'
